### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by visiky** [antvis/GUI#31]
![image](https://user-images.githubusercontent.com/15646325/125181374-b2c07200-e236-11eb-92d4-b9483de6c22b.png)

**Comment by Aarebecca** [comment]
mark了，这个会改

**Comment by hustcc** [comment]
已经改了就记得关闭，然后在 pr 中加上引用。

**Comment by Aarebecca** [comment]
> 已经改了就记得关闭，然后在 pr 中加上引用。

哦哦哦，好的
