### ISSUE TITLE
[讨论] 组件 API 设计

### ISSUE THREAD

**Issue by visiky** [antvis/GUI#65]
G 的大部分 api 设计会考虑 DOM API，那我们在做 GUI 的时候，有一些 API 属性定义参考的是 DOM API 还是 React 呢？比如：

- [x]  `onClick`,`onChange`
- [ ] or `onclick`, `onchange`

一些现状：
|组件|现象|
| ---- | --- |
| Scrollbar | ![image](https://user-images.githubusercontent.com/15646325/130192727-268cbccb-0797-4062-bbe1-d7a15d696ce6.png)|
| Button |![image](https://user-images.githubusercontent.com/15646325/130192781-271c6a73-5536-408c-8abe-779da7cfac5e.png)|

**Comment by Aarebecca** [comment]
我个人倾向驼峰式，因为全小写lint会提升拼写错误0.0

**Comment by zhanba** [comment]
驼峰没毛病
