### ISSUE TITLE
[走查] button 问题

### ISSUE THREAD

**Issue by visiky** [antvis/GUI#69]
|问题|进度|
|---|---|
|![image](https://user-images.githubusercontent.com/15646325/130539604-546185a5-df24-4f0f-84fe-aaa1c3e24fad.png)|-|
|![image](https://user-images.githubusercontent.com/15646325/130539794-5cdaf848-7936-4da5-a236-554c97bfaa1e.png)|-|

**Comment by Aarebecca** [comment]
这个应该是G 图形的边框问题，边框宽度是向外扩散的
