### ISSUE TITLE
[走查] Switch 问题

### ISSUE THREAD

**Issue by visiky** [antvis/GUI#74]
### 切换的时候，text 丢失

![image](https://user-images.githubusercontent.com/15646325/132113237-5aec21f0-98fb-4ca7-b9b4-1f6d703aa34a.png)

### 第一次点击没反应 & demo 文案需要优化下

![image](https://user-images.githubusercontent.com/15646325/132113254-7c87e49c-7398-4648-85f1-95fe22adbde4.png)

**Comment by ai-qing-hai** [comment]
切换的时候，text 丢失 （text 和 Tag 有关, tag 估计是更新了，需要重新按照tag更新的来写了）

第一次点击没反应 & demo 文案需要优化下 （ 没反应是 example  按钮初始化的 checked 为 true ，现在改为 false ）；
