### ISSUE TITLE
[走查] Tooltip 组件

### ISSUE THREAD

**Issue by visiky** [antvis/GUI#76]
![image](https://user-images.githubusercontent.com/15646325/132113505-9e1d9246-5be4-4ab4-99ec-d080c2281a99.png)

**Comment by Aarebecca** [comment]
内部对事件做了节流，默认是100ms，可以试试配置throttleFrequency参数。

**Comment by visiky** [comment]
> 内部对事件做了节流，默认是100ms，可以试试配置throttleFrequency参数。

为什么不考虑使用 denounce

**Comment by Aarebecca** [comment]
> > 内部对事件做了节流，默认是100ms，可以试试配置throttleFrequency参数。
> 
> 为什么不考虑使用 denounce

这里的情况不太适合做防抖吧😅

**Comment by visiky** [comment]
> > > 内部对事件做了节流，默认是100ms，可以试试配置throttleFrequency参数。
> > 
> > 
> > 为什么不考虑使用 denounce
> 
> 这里的情况不太适合做防抖吧😅

看了下，在 G2 里边默认是 50ms (要不改一下？)

**Comment by Aarebecca** [comment]
> > > > 内部对事件做了节流，默认是100ms，可以试试配置throttleFrequency参数。
> > > 
> > > 
> > > 为什么不考虑使用 denounce
> > 
> > 
> > 这里的情况不太适合做防抖吧😅
> 
> 看了下，在 G2 里边默认是 50ms (要不改一下？)

已经改掉了
